In [17]:
import numpy as np
from sklearn.model_selection import train_test_split

In [13]:
a = np.arange(1,101)
a

array([  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
        14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,
        27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,
        40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,  52,
        53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,  65,
        66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,  78,
        79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,  91,
        92,  93,  94,  95,  96,  97,  98,  99, 100])

In [15]:
b = np.arange(501, 601)
b

array([501, 502, 503, 504, 505, 506, 507, 508, 509, 510, 511, 512, 513,
       514, 515, 516, 517, 518, 519, 520, 521, 522, 523, 524, 525, 526,
       527, 528, 529, 530, 531, 532, 533, 534, 535, 536, 537, 538, 539,
       540, 541, 542, 543, 544, 545, 546, 547, 548, 549, 550, 551, 552,
       553, 554, 555, 556, 557, 558, 559, 560, 561, 562, 563, 564, 565,
       566, 567, 568, 569, 570, 571, 572, 573, 574, 575, 576, 577, 578,
       579, 580, 581, 582, 583, 584, 585, 586, 587, 588, 589, 590, 591,
       592, 593, 594, 595, 596, 597, 598, 599, 600])

In [ ]:
# difference between range and arange is that arange returns an array of elements while range returns list of elements

In [49]:
a_train, a_test = train_test_split(a, test_size = 0.2, random_state = 425, shuffle = True)
a_train , a_test

(array([ 57,  87,  59,  15,  72,  27,  13,  85,  11,  39,  61,   6,  33,
         32,  42,  45,  64,  37,  67,   9,  75,  68,  99,  29,  84,  81,
         70,   4,   7,   8,  73,  43,  50,  35,   1,  89,  26,  76,  19,
          3,  25,  30,  90,  79,  31,  58,  41,  18,  95,  54,  69,  55,
         93,  23,  65,  16,   2,  96,  44,  62,  51,  88,  49,  10,  48,
         24,  40,   5,  74,  21,  56,  28,  60,  20,  98,  77,  97,  83,
        100,  14]),
 array([71, 94, 17, 80, 82, 36, 78, 92, 52, 34, 47, 66, 63, 22, 12, 91, 86,
        38, 46, 53]))

In [79]:
total = train_test_split(a, b, test_size = 0.2, shuffle = False)

In [81]:
a_train = total[0]
a_test = total[1]

b_train = total[2]
b_test = total[3]

a_train, a_test

(array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
        18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
        35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51,
        52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68,
        69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80]),
 array([ 81,  82,  83,  84,  85,  86,  87,  88,  89,  90,  91,  92,  93,
         94,  95,  96,  97,  98,  99, 100]))

In [83]:
b_train, b_test

(array([501, 502, 503, 504, 505, 506, 507, 508, 509, 510, 511, 512, 513,
        514, 515, 516, 517, 518, 519, 520, 521, 522, 523, 524, 525, 526,
        527, 528, 529, 530, 531, 532, 533, 534, 535, 536, 537, 538, 539,
        540, 541, 542, 543, 544, 545, 546, 547, 548, 549, 550, 551, 552,
        553, 554, 555, 556, 557, 558, 559, 560, 561, 562, 563, 564, 565,
        566, 567, 568, 569, 570, 571, 572, 573, 574, 575, 576, 577, 578,
        579, 580]),
 array([581, 582, 583, 584, 585, 586, 587, 588, 589, 590, 591, 592, 593,
        594, 595, 596, 597, 598, 599, 600]))